<a href="https://colab.research.google.com/github/LeticiaCoitinho/A3-IA/blob/main/A3Entrega4RegressaoLogistica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn import preprocessing
from matplotlib import pyplot as plt
import seaborn as sns
sns.set()

data = pd.read_csv('Employee.csv')

data.columns
print(data.dtypes)

data.head()

Education                    object
JoiningYear                   int64
City                         object
PaymentTier                   int64
Age                           int64
Gender                       object
EverBenched                  object
ExperienceInCurrentDomain     int64
LeaveOrNot                    int64
dtype: object


Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0  Bachelors         2017  Bangalore            3   34    Male          No   
1  Bachelors         2013       Pune            1   28  Female          No   
2  Bachelors         2014  New Delhi            3   38  Female          No   
3    Masters         2016  Bangalore            3   27    Male          No   
4    Masters         2017       Pune            3   24    Male         Yes   

   ExperienceInCurrentDomain  LeaveOrNot  
0                          0           0  
1                          3           1  
2                          2           0  
3                          5           1  
4                          2           1

In [ ]:
data.drop('City',axis=1,inplace=True)
data.drop('JoiningYear', axis=1, inplace=True)

le = preprocessing.LabelEncoder()
Education_encode = le.fit_transform(data['Education'])
Gender_encode = le.fit_transform(data['Gender'])
EverBenched_encode = le.fit_transform(data['EverBenched'])
print(Education_encode)
print(Gender_encode)
print(EverBenched_encode)

[0 0 0 ... 1 0 0]
[1 0 0 ... 1 1 1]
[0 0 0 ... 0 1 1]


In [ ]:
data.isnull().sum()

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4653 entries, 0 to 4652
Data columns (total 4 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   PaymentTier                4653 non-null   int64
 1   Age                        4653 non-null   int64
 2   ExperienceInCurrentDomain  4653 non-null   int64
 3   LeaveOrNot                 4653 non-null   int64
dtypes: int64(4)
memory usage: 145.5 KB


In [ ]:
data.drop(['Education', 'Gender', 'EverBenched'], axis=1, inplace=True)

In [ ]:
X = data[['PaymentTier', 'Age', 'ExperienceInCurrentDomain', 'LeaveOrNot' ]]
X['Education'] = Education_encode
X['Gender'] = Gender_encode
y = EverBenched_encode
print(X)
print(y)

      PaymentTier  Age  ExperienceInCurrentDomain  LeaveOrNot  Education  \
0               3   34                          0           0          0   
1               1   28                          3           1          0   
2               3   38                          2           0          0   
3               3   27                          5           1          1   
4               3   24                          2           1          1   
...           ...  ...                        ...         ...        ...   
4648            3   26                          4           0          0   
4649            2   37                          2           1          1   
4650            3   27                          5           1          1   
4651            3   30                          2           0          0   
4652            3   33                          4           0          0   

      Gender  
0          1  
1          0  
2          0  
3          1  
4          1

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data.drop('Age',axis=1), data['Age'], test_size=0.40, random_state=101)
print(X_train)
print(y_test)

      PaymentTier  ExperienceInCurrentDomain  LeaveOrNot
505             3                          4           1
4203            3                          1           0
2638            2                          2           1
2336            3                          1           0
2645            3                          5           1
...           ...                        ...         ...
4079            3                          4           0
4171            2                          4           0
599             3                          2           0
1361            3                          5           1
1547            3                          5           1

[2791 rows x 3 columns]
2911    28
2182    29
497     28
4283    25
1661    28
        ..
4551    25
694     26
251     25
238     28
624     27
Name: Age, Length: 1862, dtype: int64


In [ ]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression(solver='lbfgs',max_iter=1000)

logmodel.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [ ]:
predictions = logmodel.predict(X_test)
predictions


array([28, 28, 28, ..., 28, 28, 27])

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

          22       0.18      0.21      0.20        19
          23       0.00      0.00      0.00        13
          24       0.00      0.00      0.00       155
          25       0.63      0.20      0.30       174
          26       0.59      1.00      0.74       255
          27       0.69      1.00      0.82       252
          28       0.21      0.81      0.34       252
          29       0.00      0.00      0.00       101
          30       0.00      0.00      0.00        90
          31       0.00      0.00      0.00        53
          32       0.00      0.00      0.00        54
          33       0.00      0.00      0.00        50
          34       0.00      0.00      0.00        51
          35       0.00      0.00      0.00        45
          36       0.00      0.00      0.00        54
          37       0.00      0.00      0.00        51
          38       0.00      0.00      0.00        56
          39       0.00    

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.metrics import confusion_matrix
conf_mat = confusion_matrix(y_test, predictions)
print(conf_mat)

[[  4   0   2   0   0   0  13   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  0   0   0   0   0   0  13   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  0   0   0   0   0   0 155   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  0   0   0  34  39   0 101   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  0   0   0   0 255   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  0   0   0   0   0 252   0   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  4   0   6   5  24   9 204   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  1   0   3   1  12   4  80   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  1   0   4   1   9   6  69   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  0   0   3   0  13   5  32   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  2   0   2   1  10   4  35   0   0   0   0   0   0   0   0   0   0   0
    0   0]
 [  1   0   2   2   7  10  28   0   0   0   0   0   0   0   0   0