<a href="https://colab.research.google.com/github/LeticiaCoitinho/A3-IA/blob/main/Entrega6NaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB

data = pd.read_csv("Employee.csv")

data.drop('City',axis=1,inplace=True)
data.drop('JoiningYear', axis=1, inplace=True)

le = preprocessing.LabelEncoder()
Education_encode = le.fit_transform(data['Education'])
Gender_encode = le.fit_transform(data['Gender'])
EverBenched_encode = le.fit_transform(data['EverBenched'])
print(Education_encode)
print(Gender_encode)
print(EverBenched_encode)

[0 0 0 ... 1 0 0]
[1 0 0 ... 1 1 1]
[0 0 0 ... 0 1 1]


In [ ]:
data.drop(['Education', 'Gender', 'EverBenched'], axis=1, inplace=True)

In [ ]:
X = data[['PaymentTier', 'Age', 'ExperienceInCurrentDomain', 'LeaveOrNot' ]]
X['Education'] = Education_encode
X['Gender'] = Gender_encode
y = EverBenched_encode
print(X)
print(y)

      PaymentTier  Age  ExperienceInCurrentDomain  LeaveOrNot  Education  \
0               3   34                          0           0          0   
1               1   28                          3           1          0   
2               3   38                          2           0          0   
3               3   27                          5           1          1   
4               3   24                          2           1          1   
...           ...  ...                        ...         ...        ...   
4648            3   26                          4           0          0   
4649            2   37                          2           1          1   
4650            3   27                          5           1          1   
4651            3   30                          2           0          0   
4652            3   33                          4           0          0   

      Gender  
0          1  
1          0  
2          0  
3          1  
4          1

In [ ]:
(X_train, X_test, y_train, y_test) = train_test_split(X,y)
modelo1 = GaussianNB()
modelo1.fit(X_train, y_train)
precisao1 = str(round(modelo1.score(X_test, y_test)* 100,2))+"%"
print('A acurácia do modelo 1 foi: ', precisao1)
y_pred = modelo1.predict(X_test)
print(confusion_matrix(y_test, y_pred))

A acurácia do modelo 1 foi:  90.64%
[[1055    0]
 [ 109    0]]


In [ ]:
modelo2 = MultinomialNB()
modelo2.fit(X_train, y_train)
precisao2 = str(round(modelo2.score(X_test,y_test) * 100, 2))+"%"
print('A acurácia do modelo 2 foi: ', precisao2)
y_pred = modelo2.predict(X_test)
print(confusion_matrix(y_test, y_pred))

A acurácia do modelo 2 foi:  90.64%
[[1055    0]
 [ 109    0]]


In [ ]:
modelo3 = BernoulliNB()
modelo3.fit(X_train,y_train)
precisao3 = str(round(modelo3.score(X_test,y_test) * 100, 2))+"%"
print("A acurácia do modelo 3 foi",precisao3)
y_pred = modelo3.predict(X_test)
print(confusion_matrix(y_test, y_pred))

A acurácia do modelo 3 foi 90.64%
[[1055    0]
 [ 109    0]]
